# Generated by Django 4.2.14 on 2024-07-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('recipe1', models.CharField(blank=True, max_length=100, null=True)),
                ('recipe2', models.CharField(blank=True, max_length=100, null=True)),
                ('recipe3', models.CharField(blank=True, max_length=100, null=True)),
                ('recipe4', models.CharField(blank=True, max_length=100, null=True)),
                ('recipe5', models.CharField(blank=True, max_length=100, null=True)),
                ('recipe6', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
