# Generated by Django 4.2.14 on 2024-07-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='items',
            field=models.ManyToManyField(related_name='notes', to='api.item'),
        ),
    ]
