# Generated by Django 4.2.14 on 2024-07-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_note_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='items',
            field=models.ManyToManyField(to='api.item', verbose_name='list of items'),
        ),
    ]
