# Generated by Django 4.2.14 on 2024-07-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_note_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='items',
            field=models.ManyToManyField(related_name='notes', to='api.item'),
        ),
    ]
