# Generated by Django 4.2.14 on 2024-07-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_note_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(),
        ),
    ]
